### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by jignesh87** [jhirbour/phpqueue#1]
Hello john,
I have read php queue on"http://squirrelshaterobots.com/programming/php/building-a-queue-server-in-php-part-1-understanding-the-project/" from there i reached ti you.
I have a question how to use your package?,also how to run it in my application.
I want to queue system of file uploading.
Thanks,
Jignesh.

**Comment by jhirbour** [comment]
@jignesh87 to be honest. This project was a test for something I was working on at my former job. Using PHP FIFO files doesn't really scale well. I would recommend you look into http://www.rabbitmq.com/  or some other actual queueing service (RabbitMQ, side kick, resque).

**Comment by jignesh87** [comment]
Thank you for reply.
Jignesh
